"""
Human-readable Markdown assessment report generator.

Turns a benchmark results JSON (either schema this repo produces) into a
CISO-facing Markdown report — the Tier 1 deliverable required before this
tool is shown to an enterprise buyer (CLAUDE.md Section 6, "industry-adoption
standards").

Accepts either JSON schema currently produced in this repo:
  - ``scripts/run_ikea.py``'s schema: ``{"run": {...}, "findings": [...]}``.
    No ground-truth dataset is scored against, so only ASR is computed here
    (finding_count / max_queries); EE/CRR/SS are not available.
  - ``scripts/run_benchmark.py``'s schema: ``{"run_metadata": {...},
    "metrics": {...}, "findings": [...]}``. Full EE/ASR/CRR/SS against a
    ground-truth dataset, plus the paper-baseline comparison.

**2026-07-13 rewrite:** findings are now classified by an LLM-as-judge
(``IKEAAttack._classify_leak``, see aginiti/attacks/dra/ikea.py) rather than
by query-response embedding similarity. This report reflects that: only
findings with ``leak_type != "none"`` are shown as numbered findings, bucketed
into Critical/High/Medium sections; everything else is rolled into a single
"Non-Findings" summary line rather than listed individually.

Authorized use only — see the root README and aginiti/attacks/dra/README.md
for this tool's scope and safety notes.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

# OWASP LLM Top 10 (2025) mapping, keyed by LeakFinding.attack_type. DRA
# (Data Reconstruction Attack) extracts sensitive content from a RAG store,
# which is squarely LLM06:2025. MIA/FIA are not yet implemented in this
# library (see CLAUDE.md build-status table) — no mapping guessed for them
# ahead of time; _OWASP_DEFAULT covers any attack_type not in this dict.
_OWASP_MAPPING = {
    "DRA": "LLM06:2025 - Sensitive Information Disclosure",
    # MIA (InterrogationAttack, added 2026-07-30): a confirmed membership
    # verdict is itself a sensitive information disclosure (existence of a
    # record can be sensitive independent of content — e.g. confirming a
    # specific patient/whistleblower/customer record's presence) — same
    # OWASP category as DRA, distinct attack mechanism.
    "MIA": "LLM06:2025 - Sensitive Information Disclosure",
}
_OWASP_DEFAULT = "OWASP LLM Top 10 mapping not yet defined for this attack type"

# Paper-reported reference numbers (arXiv:2505.15420 Table 1, LLaMA + MPNet,
# No Defense row) — same source scripts/run_benchmark.py uses. Hardcoded, not
# measured; shown for context only.
_PAPER_BASELINE = {"asr": 0.92, "ee": 0.87, "crr": 0.28, "ss": 0.71}

# Attack registry key -> display name. Only "ikea" exists today. NOTE: cites
# the paper as "arXiv:2505.15420" only — every other reference to this paper
# in this codebase (CLAUDE.md, docs/, ikea.py) cites it as an arXiv preprint,
# with no ICLR (or any venue) acceptance documented anywhere in this project.
# Do not add a venue/year claim here without a verified source.
_ATTACK_DISPLAY_NAMES = {
    "ikea": "IKEA (Silent Leaks, arXiv:2505.15420)",
}

_FULL_RESPONSE_TRUNCATE_CHARS = 200

# Display labels for known target_toggle_state keys (see _normalize's
# "target_toggle_state" field) — generic and extensible on purpose: any
# future defense/attack target that reports a "<name>_enabled" key not
# listed here still renders correctly via the fallback in _toggle_label,
# just without a hand-tuned label. Not hardened_agent-specific despite
# hardened_agent being the first real caller.
_TOGGLE_LABELS = {
    "rbac_enabled": "RBAC",
    "rate_limit_enabled": "Rate Limiting",
    "redaction_enabled": "Output Redaction",
    "memory_enabled": "Conversation Memory",
    "guardrail_enabled": "System-Prompt Guardrail",
}


def _toggle_label(key: str) -> str:
    if key in _TOGGLE_LABELS:
        return _TOGGLE_LABELS[key]
    return key.replace("_enabled", "").replace("_", " ").title()


def _format_runtime(seconds: float) -> str:
    minutes, secs = divmod(int(round(seconds)), 60)
    return f"{minutes}m {secs}s"


def _truncate(text: str, n: int) -> str:
    text = text or ""
    return text[:n] + ("..." if len(text) > n else "")


def _normalize(report: dict) -> dict:
    """Extract a common shape from either JSON schema this repo produces.

    ``queries_sent``/``refused_queries`` (added 2026-07-2x): both scripts
    now record the queries actually sent and which ones were refused (see
    ``IKEAAttack.refused_queries`` in aginiti/attacks/dra/ikea.py). Reports
    generated by an OLDER version of either script won't have these keys —
    ``.get(...)`` with a same-as-budget/empty-list fallback keeps this
    function working on those legacy files without raising, but for a
    legacy file the fallback ``queries_sent`` is just a guess (assumes the
    full budget was sent and nothing was refused), not a real recovered
    count — that data was never captured and can't be reconstructed after
    the fact.
    """
    if "run_metadata" in report:
        meta = report["run_metadata"]
        return {
            "target": meta["agent_url"],
            "queries": meta["total_queries"],
            "queries_sent": meta.get("queries_sent", meta["total_queries"]),
            "runtime_seconds": meta["runtime_seconds"],
            "timestamp": meta["timestamp"],
            "embed_model": meta["embed_model"],
            "llm_provider": meta.get("llm_provider", ""),
            "attack": meta["attack"],
            "findings": report["findings"],
            "refused_queries": report.get("refused_queries", []),
            "metrics": report.get("metrics"),
            "authorized_by": meta.get("authorized_by"),
            "engagement_id": meta.get("engagement_id"),
            # Both optional, generic (not hardened_agent-specific) —
            # populated via run_benchmark()'s extra_run_metadata by any
            # caller that authenticates as a specific identity and/or has
            # independently-toggleable target-side defenses to report.
            # First real caller: scripts/run_ikea_hardened.py. Absent
            # for callers that don't set these (e.g. run_healthcare_benchmark.py).
            "persona": meta.get("persona"),
            "target_toggle_state": meta.get("target_toggle_state"),
        }
    if "run" in report:
        meta = report["run"]
        refused_queries = report.get("refused_queries", [])
        return {
            "target": meta["target_url"],
            "queries": meta["max_queries"],
            # Fallback matches the run_metadata branch above: assume the
            # full budget was sent when queries_sent isn't recorded (a
            # legacy file, from before this field existed) — NOT
            # len(findings)+len(refused_queries), which would silently
            # undercount for any legacy file that had real refusals the old
            # schema never captured.
            "queries_sent": meta.get("queries_sent", meta["max_queries"]),
            "runtime_seconds": meta["duration_seconds"],
            "timestamp": meta["started_at"],
            "embed_model": meta.get("embed_model", ""),
            "llm_provider": meta.get("llm_provider", ""),
            "attack": "ikea",
            "findings": report["findings"],
            "refused_queries": refused_queries,
            "metrics": None,
            "authorized_by": meta.get("authorized_by"),
            "engagement_id": meta.get("engagement_id"),
            "persona": meta.get("persona"),
            "target_toggle_state": meta.get("target_toggle_state"),
        }
    raise ValueError(
        "Unrecognized report schema — expected a 'run_metadata' key "
        "(scripts/run_benchmark.py output) or a 'run' key "
        "(scripts/run_ikea.py output)."
    )


def _redact(text: str, label: str) -> str:
    """
    Placeholder for a redacted report (added 2026-07-2x) — preserves enough
    information to know *something* of a given size and category existed,
    without reproducing the literal leaked content. Used when
    ``generate_markdown_report(..., redact=True)``.
    """
    text = text or ""
    return f"[REDACTED — {len(text)} chars of {label}]"


_SEVERITY_RANK = {"critical": 4, "high": 3, "medium": 2, "low": 1, "none": 0}


def _overall_risk_verdict(reportable: list[dict]) -> str:
    """
    One-line top-of-report verdict (added 2026-07-2x) — a CISO skimming this
    report gets a bottom line before the detail tables. Ranked by the worst
    severity among CONFIRMED findings (leak_type in pii/verbatim/
    sensitive_data) first; falls back to the worst severity among ANY
    reportable finding (e.g. schema-only) if nothing is confirmed, since a
    structural disclosure is still worth surfacing, just labeled honestly as
    not a confirmed data leak.
    """
    if not reportable:
        return (
            "NONE DETECTED — see the coverage note below; absence of "
            "findings within this run's query budget is not a safety guarantee."
        )
    confirmed = [f for f in reportable if f.get("confirmed")]
    pool = confirmed if confirmed else reportable
    worst = max(pool, key=lambda f: _SEVERITY_RANK.get(f.get("severity", "low"), 0))
    label = (
        "confirmed data disclosure"
        if confirmed
        else "structural disclosure only — no confirmed data leak"
    )
    return f"{worst.get('severity', 'low').upper()} ({label})"


def _bucket(findings: list[dict]) -> dict[str, list[dict]]:
    """
    Split findings (already filtered to leak_type != "none") into
    Critical/High/Medium buckets.

    Priority order (judgment call — the three named sections in the spec
    overlap at the edges, e.g. a leak_type="sensitive_data" finding the
    classifier marked severity="critical"): every leak_type != "none"
    finding must land in exactly one bucket, none silently dropped.

    1. leak_type in (pii, verbatim), or severity == "critical" -> Critical
       (pii/verbatim are inherently the most severe categories regardless
       of what severity string the classifier attached).
    2. severity == "high" -> High.
    3. Everything else (medium, low, or any other value) -> Medium, as the
       catch-all so a leak_type="schema"/"sensitive_data" finding with
       severity="low" is still surfaced rather than disappearing.
    """
    buckets: dict[str, list[dict]] = {"critical": [], "high": [], "medium": []}
    for f in findings:
        leak_type = f.get("leak_type", "unknown")
        severity = f.get("severity", "")
        if leak_type in ("pii", "verbatim") or severity == "critical":
            buckets["critical"].append(f)
        elif severity == "high":
            buckets["high"].append(f)
        else:
            buckets["medium"].append(f)
    return buckets


def _render_finding(f: dict, index: int, attack_code: str, redact: bool = False) -> list[str]:
    sev = f.get("severity", "").upper()
    owasp = _OWASP_MAPPING.get(f.get("attack_type", ""), _OWASP_DEFAULT)

    # Confirmed-vs-schema status line (added 2026-07-2x): without this, a
    # schema-only disclosure (structure/field names, no real record content)
    # sits visually identical to a genuine pii/verbatim/sensitive_data leak
    # in the same severity section — an analyst triaging "what do I fix
    # first" couldn't tell them apart without cross-referencing the JSON's
    # leak_type field. Reuses the finding's own `confirmed` field (already
    # computed by IKEAAttack._make_finding — leak_type in
    # aginiti.attacks.dra.ikea._CONFIRMED_LEAK_TYPES) rather than
    # re-deriving it here, so this can never drift out of sync with what
    # the attack itself decided.
    leak_type = f.get("leak_type", "unknown")
    if f.get("confirmed"):
        status = f"CONFIRMED DATA LEAK ({leak_type})"
    else:
        status = f"Not confirmed as a data leak ({leak_type} — structure/uncertain, not verified record content)"

    leaked_content = f.get("leaked_content", "")
    full_response = f.get("full_response", "")
    leaked_display = _redact(leaked_content, "leaked content") if redact else leaked_content
    full_response_display = (
        _redact(full_response, "full response") if redact
        else _truncate(full_response, _FULL_RESPONSE_TRUNCATE_CHARS)
    )

    lines = [
        f"### Finding {attack_code}-{index:03d} [{sev}]",
        f"**Status:** {status}",
        f"**Probe:** \"{f.get('probe_used', '')}\"",
        f"**What leaked:** {leaked_display}",
        f"**Why flagged:** {f.get('reasoning', '')}",
        f"**Confidence:** {f.get('confidence', 0):.2f}",
        f"**OWASP LLM:** {owasp}",
        f"**Remediation:** {f.get('recommendation', '')}",
        f"**Full response (truncated):** {full_response_display}",
        "",
    ]
    return lines


def generate_markdown_report(
    report: dict, output_path: str | Path, redact: bool = False
) -> str:
    """
    Render ``report`` as a human-readable Markdown assessment report and
    write it to ``output_path``.

    ``report`` is a benchmark results dict in either schema this repo
    produces (see module docstring). Returns the rendered Markdown string.

    ``redact`` (added 2026-07-2x): when ``True``, every finding's leaked
    content and full response are replaced with a size/category placeholder
    (see ``_redact``) instead of the literal text — the report itself
    otherwise reproduces real extracted sensitive data verbatim, which makes
    the report file a sensitive artifact in its own right. Everything else
    (severity, leak_type, probe, reasoning, recommendation, OWASP mapping)
    is preserved, so a redacted report still conveys what was found and how
    severe it is, just not the literal content — suitable for wider
    circulation (leadership, external auditors) than the full-detail report.
    Callers typically generate both from the same run (see
    ``scripts/run_benchmark.py``/``scripts/run_ikea.py``).
    """
    data = _normalize(report)
    findings = data["findings"]

    # "Confirmed leaks only" (spec) — leak_type="none" findings are real
    # LeakFinding objects (every non-refused response gets classified) but
    # are deliberately excluded from the Risk Summary / numbered findings,
    # and rolled into a single Non-Findings summary line instead.
    reportable = [f for f in findings if f.get("leak_type", "none") != "none"]
    non_findings_count = len(findings) - len(reportable)

    # Global finding IDs (fixed 2026-07-2x): assigned once, in query order,
    # BEFORE bucketing by severity — previously each severity section
    # (Critical/High/Medium) numbered its own findings starting at 1
    # independently, so e.g. "Finding IKEA-001 [HIGH]" and a completely
    # different "Finding IKEA-001 [MEDIUM]" could both exist in the same
    # report with the same ID. A real problem for any workflow that
    # references a finding by ID (ticketing, remediation tracking,
    # "has IKEA-001 been fixed yet") — IDs must be unique across the whole
    # report, not just within one section.
    finding_ids = {id(f): i for i, f in enumerate(reportable, start=1)}

    severity_order = ["critical", "high", "medium", "low"]
    severity_counts = {s: 0 for s in severity_order}
    for f in reportable:
        sev = f.get("severity", "low").lower()
        if sev in severity_counts:
            severity_counts[sev] += 1

    date_str = data["timestamp"][:10] if data["timestamp"] else ""
    attack_display = _ATTACK_DISPLAY_NAMES.get(data["attack"], data["attack"])
    attack_code = data["attack"].upper()

    lines: list[str] = []
    lines.append("# Aginiti DRA Assessment Report")
    if redact:
        lines.append(
            "**[REDACTED VERSION — leaked content and full responses are "
            "masked below. See the full-detail report for literal evidence.]**"
        )
    lines.append(f"**Target:** {data['target']}")
    lines.append(f"**Date:** {date_str}")
    lines.append(f"**Attack:** {attack_display}")
    # queries_sent vs. queries (budget): shown together whenever they differ
    # so a run that stopped early (rate limit, endpoint failure, ...) is
    # visible at a glance here, not just inferable from the JSON.
    queries_str = f"{data['queries']}"
    if data["queries_sent"] != data["queries"]:
        queries_str = f"{data['queries_sent']} sent (of {data['queries']} budgeted — stopped early)"
    lines.append(
        f"**Queries:** {queries_str} | "
        f"**Runtime:** {_format_runtime(data['runtime_seconds'])}"
    )
    # Authorization/engagement record (added 2026-07-2x). Optional — this
    # library has no way to enforce that a test was actually authorized,
    # only a place to record it if the caller supplies one. When absent, a
    # visible reminder is shown rather than silently omitting any mention of
    # it, consistent with this project's "authorized use only" stance
    # (root README / aginiti/attacks/dra/README.md).
    if data.get("authorized_by") or data.get("engagement_id"):
        parts = []
        if data.get("authorized_by"):
            parts.append(f"**Authorized by:** {data['authorized_by']}")
        if data.get("engagement_id"):
            parts.append(f"**Engagement:** {data['engagement_id']}")
        lines.append(" | ".join(parts))
    else:
        lines.append(
            "**Authorization:** Not recorded for this run — confirm this "
            "test was authorized before relying on this report."
        )
    lines.append("")

    lines.append(f"**Overall Risk:** {_overall_risk_verdict(reportable)}")
    lines.append("")
    lines.append(
        "> **Coverage note:** this assessment sampled "
        f"{data['queries_sent']} quer{'y' if data['queries_sent'] == 1 else 'ies'} "
        "against the target — it is not exhaustive. Absence of a finding for "
        "a given query means no leak was found within this query budget, "
        "not that the system is safe on that topic. EE/CRR/SS below are "
        "computed over a small sample and carry real run-to-run variance — "
        "treat them as directional, not precise, especially at low query counts."
    )
    lines.append("")

    # Target Configuration (added 2026-08-10): generic, not hardened_agent-
    # specific despite that being the first real caller — renders whenever
    # a run recorded a persona/identity and/or a target-side toggle state
    # via extra_run_metadata (see _normalize). Silently omitted for runs
    # that don't set either (e.g. run_healthcare_benchmark.py), rather than
    # showing an empty/misleading section.
    persona = data.get("persona")
    toggle_state = data.get("target_toggle_state")
    if persona or toggle_state:
        lines.append("## Target Configuration")
        if persona:
            lines.append(f"**Authenticated as:** {persona}")
        if isinstance(toggle_state, dict) and toggle_state:
            lines.append("")
            lines.append("| Defense | State |")
            lines.append("|---------|-------|")
            for key, value in toggle_state.items():
                lines.append(f"| {_toggle_label(key)} | {'On' if value else 'Off'} |")
        elif isinstance(toggle_state, str):
            # e.g. "unknown (config fetch failed)" -- run_ikea_hardened.py's
            # fallback when /config couldn't be reached at run time.
            lines.append(f"**Target toggle state:** {toggle_state}")
        lines.append("")

    lines.append("## Risk Summary")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in severity_order:
        if severity_counts[sev] > 0:
            lines.append(f"| {sev.capitalize()} | {severity_counts[sev]} |")
    if not reportable:
        lines.append("| (none) | 0 |")
    lines.append("")

    metrics = data["metrics"]
    lines.append("## Key Metrics")
    lines.append("| Metric | Value | Paper Baseline |")
    lines.append("|--------|-------|----------------|")
    if metrics is not None:
        lines.append(
            f"| ASR | {metrics['asr'] * 100:.0f}% | "
            f"{_PAPER_BASELINE['asr'] * 100:.0f}% |"
        )
        lines.append(f"| EE | {metrics['ee']:.2f} | {_PAPER_BASELINE['ee']:.2f}* |")
        lines.append(
            f"| CRR | {metrics['crr_mean']:.2f} | {_PAPER_BASELINE['crr']:.2f} |"
        )
        lines.append(f"| SS | {metrics['ss_mean']:.2f} | {_PAPER_BASELINE['ss']:.2f} |")
    else:
        # queries_sent, not the budget ("queries") — an ASR computed against
        # the budget would be artificially low for a run that stopped early
        # (rate limit, endpoint failure, ...) for reasons unrelated to the
        # attack's actual success rate against what it did send.
        asr = (len(findings) / data["queries_sent"]) if data["queries_sent"] else 0.0
        lines.append(f"| ASR | {asr * 100:.0f}% | {_PAPER_BASELINE['asr'] * 100:.0f}% |")
    lines.append(
        f"| Classifier | LLM-as-judge ({data['llm_provider']}) | — |"
    )
    lines.append("")
    if metrics is not None:
        lines.append(
            "*Paper used all-mpnet-base-v2 embeddings on both attacker and "
            "target. See Methodology below."
        )
    else:
        lines.append(
            "*EE/CRR/SS require scoring against a ground-truth dataset, not "
            "available for this run. Use `scripts/run_benchmark.py` against "
            "a ground-truth dataset (e.g. HealthCareMagic-1k) for full "
            "metric scoring."
        )
    lines.append("")

    buckets = _bucket(reportable)

    lines.append("## Critical Findings")
    if not buckets["critical"]:
        lines.append("No critical findings in this run.")
        lines.append("")
    else:
        for f in buckets["critical"]:
            lines.extend(_render_finding(f, finding_ids[id(f)], attack_code, redact))

    lines.append("## High Findings")
    if not buckets["high"]:
        lines.append("No high-severity findings in this run.")
        lines.append("")
    else:
        for f in buckets["high"]:
            lines.extend(_render_finding(f, finding_ids[id(f)], attack_code, redact))

    lines.append("## Medium Findings")
    if not buckets["medium"]:
        lines.append("No medium-severity findings in this run.")
        lines.append("")
    else:
        for f in buckets["medium"]:
            lines.extend(_render_finding(f, finding_ids[id(f)], attack_code, redact))

    lines.append("## Non-Findings Summary")
    lines.append(
        f"{non_findings_count} of {len(findings)} responses contained no "
        "evidence of protected data leakage."
    )
    lines.append("")

    lines.append("## Methodology")
    tiers = {f.get("tier_used", "black_box") for f in findings} or {"black_box"}
    if tiers == {"black_box"}:
        lines.append(
            "Attack type: Data Reconstruction (DRA), Tier 1 black-box. "
            "No access to retriever, embedding model, or system prompt required."
        )
    else:
        lines.append(
            "Attack type: Data Reconstruction (DRA), Tier 2 (OTel-confirmed) "
            "for findings cross-referenced against retrieval spans; "
            "unconfirmed findings remain Tier 1 black-box."
        )
    lines.append(
        f"Embedding model: `{data['embed_model']}` (local ONNX, no API cost). "
        "The IKEA paper used all-mpnet-base-v2 — this project's default is "
        "all-MiniLM-L6-v2 (same family, smaller), used symmetrically on both "
        "attacker and target, so numbers differ from the paper's Table 1 for "
        "embedding-space reasons, not an attacker/target mismatch."
    )
    lines.append(
        f"Leak classification: every non-refused response is separately "
        f"reviewed by an LLM-as-judge ({data['llm_provider']}) that "
        "determines leak_type, severity, and the specific evidence quote — "
        "severity is no longer derived from query-response embedding "
        "similarity, which measured topical relevance, not confirmed "
        "leakage. Adds one LLM call per non-refused response."
    )
    if metrics is not None:
        lines.append(
            "EE counts a document as \"recovered\" using Rouge-L "
            "**precision** against the finding's evidence quote, not "
            "F-measure — precision measures how much of the quote is found "
            "in the source, and unlike F-measure's recall term, isn't "
            "penalized by the source document's overall length (a short, "
            "fully accurate quote against a long multi-paragraph document "
            "would otherwise score far below threshold on length alone). "
            "CRR above still uses F-measure, for comparability with the "
            "paper's Table 1."
        )
    lines.append("")

    lines.append("## Refused Queries")
    refused_queries = data["refused_queries"]
    if not refused_queries:
        lines.append(
            "No refused-query data recorded for this run (either zero "
            "refusals occurred, or this run predates refusal tracking)."
        )
        lines.append("")
    else:
        lines.append(
            f"{len(refused_queries)} of {data['queries_sent']} queries sent "
            "were refused by the target and excluded from the findings above "
            "(recorded here for completeness — refusal detection is a "
            "heuristic, see aginiti/attacks/dra/README.md):"
        )
        lines.append("")
        for i, r in enumerate(refused_queries, start=1):
            lines.append(f"{i}. **Probe:** \"{r.get('probe', '')}\"")
            lines.append(
                f"   **Response:** "
                f"{_truncate(r.get('response', ''), _FULL_RESPONSE_TRUNCATE_CHARS)}"
            )
        lines.append("")

    markdown = "\n".join(lines) + "\n"

    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown, encoding="utf-8")
    return markdown


def generate_markdown_report_from_file(
    json_path: str | Path, redact: bool = False
) -> Path:
    """
    Load a benchmark results JSON from disk and write the corresponding
    Markdown report alongside it (same path, ``.md`` suffix instead of
    ``.json`` — or ``_redacted.md`` when ``redact=True``). Returns the
    output path.
    """
    json_path = Path(json_path)
    report = json.loads(json_path.read_text(encoding="utf-8"))
    suffix = "_redacted.md" if redact else ".md"
    output_path = json_path.with_name(json_path.stem + suffix)
    generate_markdown_report(report, output_path, redact=redact)
    return output_path


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("Usage: python -m aginiti.reporting.markdown_report <results.json>")
        sys.exit(1)
    written = generate_markdown_report_from_file(sys.argv[1])
    print(f"Wrote {written}")
